[book]
language = "en"
multilingual = false
src = "docs"
title = "Paisano TUI Book"

[build]
build-dir = "docs/build"

[output]
[output.html]
additional-css = ["./mdbook-paisano-preprocessor.css"]

[output.linkcheck]

[preprocessor]
