[book]
language = "en"
multilingual = false
src = "docs"
title = "Paisano TUI Book"

[build]
build-dir = "docs/build"

[output]
[output.html]
additional-css = ["./mdbook-paisano-preprocessor.css"]

[output.linkcheck]

[preprocessor.paisano-preprocessor]
assets_version = "0"
command = "mdbook-paisano-preprocessor"
registry = ".#__std.init"

[[preprocessor.paisano-preprocessor.multi]]
cell = "tui"
chapter = "TUI Reference"
