post_bump_hooks = [
  "git push",
  "git push origin {{version}}",
  "cog -q changelog --at {{version}}",
]

[changelog]
path = "CHANGELOG.md"
template = "remote"
remote = "github.com"
repository = "paisano-nix"
owner = "tui"
authors = [{ username = "blaggacao", signature = "David Arnold" }]
